Add policy to grant access to static.synapse.org
Sage-Bionetworks/synapseprod-infra pull request #65
Opened 2020-12-07 19:10 UTC by nickgros

And also give that access to me because I can't upload to this bucket and I need to

2020-12-07 21:24 UTC, ahayden requested changes
Looks fine, just one question.... Also, please comment is there's a ticket number for this.

2020-12-07 21:24 UTC, ahayden commented on templates/accounts.yaml
> +  AWSIAMStaticSynapseUsersGroup:
Is it reasonable to rename this group something like `AWSIAMWebEngineerUsersGroup`?

2020-12-07 21:31 UTC, nickgros commented on templates/accounts.yaml
> +  AWSIAMStaticSynapseUsersGroup:
Good idea. Will make that change

2020-12-07 21:31 UTC, nickgros commented
No ticket number. Should I create a ticket?

2020-12-07 22:18 UTC, zaro0508 commented
instead of adding more AWS users/groups why don't we just work on the existing PR federate jumpcloud users/group into this account? https://github.com/Sage-Bionetworks/synapseprod-infra/pull/55

2020-12-07 22:24 UTC, ahayden commented
Let's get a perspective from Bruce on going the federation route instead

2020-12-08 17:03 UTC, nickgros commented
How close is the JC federation to being applied? This is a blocker for me. Could we add the proposed group and then remove it later?

2020-12-08 18:46 UTC, ahayden approved these changes
Approving as necessary to unblock work before migrating to federated access

2020-12-08 19:50 UTC, nickgros commented
@ahayden Not sure if you are waiting on @brucehoff 's review, but I don't have permission to merge this if you think it is ok to merge.

2020-12-08 20:46 UTC, merged

2020-12-08 20:50 UTC, brucehoff commented
I'm curious why @nickgros (or any individual engineer) needs access to a production bucket.  If the bucket contains static content that is part of Synapse then shouldn't upload to the bucket be done by an automated CI/CD process rather than by an engineer?  I.e., shouldn't there be a Jenkins job running on an EC2 that has a _role_ that lets it deploy content to the bucket?